### ISSUE TITLE
Dictionary synthesis fails when used with a variant index set

### ISSUE THREAD

**Issue by oxinabox** [google-research/dex-lang#289] opened 2020-11-23 17:00 UTC
I was looking for functions to concatenate tables, but could not find any in the prelude.
Have I missed them, or are they not there?

**Comment by apaszke** [comment] 2020-11-23 18:05
Yeah I don't think we have a prelude function for that. Is this what you're looking for?
```
concatenate (x : n=>a) (y : m=>a) : (n|m)=>a =
  for i. case i of
    Left xi  -> x.xi
    Right yi -> y.yi
```

**Comment by oxinabox** [comment] 2020-11-23 18:16
> Is this what you're looking for?

I don't think so.
Though I am not sure what `case` or `n|m` does.

I want
`concatenate [1, 2, 3] [10, 20, 30] == [1, 2, 3, 10, 20, 30]`
trying that code you posted, it seems to just error.

**Comment by apaszke** [comment] 2020-11-24 10:11
Sorry that was a quick and hacky implementation and I did forget the `def` keyword. Anyway, try this:
```
def concatenate (x : n=>a) (y : m=>a) : ({ left: n | right: m |})=>a =
  for i. case i of
    {| left=xi |}  -> x.xi
    {| right=yi |} -> y.yi

concatenate [1, 2, 3] [10, 20, 30]
```
The `{| left: n | right: m |}` is a sum type of `n` and `m`. I.e. the valid values of that type are of the form `{| left=ni |}` (for any `ni : n`) and `{| right=mi |}` (for any `mi : m`). Which means that the number of its values is `n + m`, which is the same as the length of the concatenated array.

**Comment by oxinabox** [comment] 2020-11-24 14:49
Nice. That is really cool. I get it, it is indexed with the sum type, rather than with a simple range like `Fin 6`.
However, that leads to other problems.
It seems not to know it is a `VSpace` anymore

```
def concatenate (x : n=>a) (y : m=>a) : ({ left: n | right: m |})=>a =
  for i. case i of
    {| left=xi |}  -> x.xi
    {| right=yi |} -> y.yi

a = concatenate [1, 2, 3] [10, 20, 30]

:p a
[1, 2, 3, 10, 20, 30]@{left: Fin 3 | right: Fin 3}

:p argmin a
{| left = 0@Fin 3 |}

:p neg a
Type error:Couldn't synthesize a class dictionary for: (VSpace ({left: Fin 3 | right: Fin 3} => Int32))

:p neg a
   ^^^^
```

**Comment by apaszke** [comment] 2020-11-25 12:24
This is weird, I don't understand why didn't the synthesis find an overload. cc @dougalm

**Comment by danieldjohnson** [comment] 2021-01-22 01:01
After #480, it appears that the root cause is that we can't synthesize `VSpace Int32`. With an understandable reason: we didn't implement that, because our `VSpace` requires scaling by floats.

**Comment by dougalm** [comment] 2023-02-13 22:46
Closing as obsolete

**Closed by dougalm** 2023-02-13 22:46 UTC
