### ISSUE TITLE
Automate GitHub Pages generation

### ISSUE THREAD

**Issue by dan-zheng** [google-research/dex-lang#477] opened 2021-01-20 20:27 UTC
## Task

We can use GitHub Actions to automate GitHub Pages updates: running `make docs` and pushing the output to `gh-pages` branch. So far, we've been updating `gh-pages` branch manually.

Automation suggested here: https://github.com/google-research/dex-lang/pull/472#issuecomment-763909228

## Considerations

- [ ] `gh-pages` branch currently has some hardcoded stop-gap HTML redirection pages, added in https://github.com/google-research/dex-lang/pull/392. We should consider what to do with those - maybe we're okay with dropping those pages by now.

**Comment by oxinabox** [comment] 2021-01-20 20:31
possible duplicate of #291

**Comment by srush** [comment] 2021-01-20 21:36
You could just check those pages into `docs/`

**Comment by apaszke** [comment] 2021-01-21 09:55
I'll close this since it's a duplicate. About checking in to `docs/`, I don't see how this simplifies things. Checking in to `main` is equally hard as checking in to `gh-pages`, with the latter also having the benefit of being accessible via a URL that skips the GitHub UI.

**Closed by apaszke** 2021-01-21 09:55 UTC
Labels: maintenance

**Comment by srush** [comment] 2021-01-21 11:47
Oh I just meant if there were a fixed set of extra static landing pages you could check them in somewhere.

The main suggestion was to use GitHub actions to generate the gh-pages. GitHub actions could also generate these static pages as well.

**Comment by apaszke** [comment] 2021-01-21 13:34
I'm not sure if I follow. `gh-pages` is already the branch that contains the check in of those static pages.

**Comment by srush** [comment] 2021-01-21 14:29
If we move to a world where gh-pages is an automatically built branch, then one setup would be to just deploy clean to it every time master is updated by rebuilding the html pages in GitHub actions. 

@dan-zheng was worried that this would make it difficult to *also* have manually created html pages there. 

One solution would be to move those manual pages somewhere else, another would be to only update the non manual part of the branch, a final solution would be to have no manual pages and just autogen placeholders. 

This is not an interesting problem.
