### ISSUE TITLE
Reading bigger files

### ISSUE THREAD

**Issue by srush** [google-research/dex-lang#599] opened 2021-07-15 12:16 UTC
Is there a way to read files with more than 4096 byte?

**Comment by srush** [comment] 2021-07-15 16:45
Figured this out.

**Comment by apaszke** [comment] 2021-07-16 09:10
Let's keep this open anyway. This artificial limit is a footgun waiting to fire.

**Comment by axch** [comment] 2022-05-19 00:39
Is this still an issue?  The only place I see 4096 is the chunk size inside the definition of `fread` in the prelude, but reading that code, I don't see a limit on the size of files that can be read.  I also just tried a 21kb file and `read_file` read it without difficulty.

I would just close this issue as non-reproducible, except the code for `fread` doesn't seem to have changed since late 2020, so perhaps I am looking in the wrong place?

**Comment by apaszke** [comment] 2022-05-19 10:57
This used to be an issue with an early implementation of `fread`, but it was fixed a long time ago. This should be good to close!

**Closed by apaszke** 2022-05-19 10:57 UTC
Labels: language / frontend, libraries
