### ISSUE TITLE
`scan` (and other stateful loops) don't seem to work well with data classes.

### ISSUE THREAD

**Issue by sschoenholz** [google-research/dex-lang#694] opened 2021-11-22 17:53 UTC
Hi! I was playing around with dex over the weekend and had a great time. I think I either don't understand the semantics of scan or there's a codepath that's not implemented yet. In anycase, I thought I would bring it up here. If I'm doing something stupid, please let me know.

Here's some code:
```
 data Thing = T {a: Float}
 
 scan_over : n=>Float -> n=>Float =
   \xs. snd $ scan (T {a=1.0}) \i t.
     (T {a}) = t
     (T {a=a + xs.i}, a)
 
 scan_over_2 : n=>Float -> n=>Float =
   \xs. snd $ scan 1.0 \i t.
     (t + xs.i, t)
```

Writing `scan_over_2 [1.0, 2.0, 3.0]` works fine. However, writing `scan_over [1.0, 2.0, 3.0]` throws
```
dex: Not implemented
CallStack (from HasCallStack):
  error, called at src/lib/Type.hs:641:18 in dex-0.1.0.0-2yMrYnoOO1jGVtE2NeBrco:Type
```

Also, not exactly related but writing `scan_over_2 $ for i: (Fin 3=>Float). 1.0` throws
```
dex: Not implemented ((Fin 3) => Float32)
CallStack (from HasCallStack):
  error, called at src/lib/Builder.hs:948:20 in dex-0.1.0.0-2yMrYnoOO1jGVtE2NeBrco:Builder
```
which I find a bit odd since I would have thought that this produces the same code as the first example that works (isn't the type of [1.0, 2.0, 3.0] also Fin 3=>Float)?

Thanks for the help! Also, no rush on this.

**Comment by dougalm** [comment] 2021-11-22 18:41
Hey Sam, glad to hear you're playing around with it! Let us know if we can help in any way. It would be cool to try some molecular dynamics sims.

Thanks for the bug report. It's a known (bad) issue: #529. Also related: #672 and #609.

For background, `scan` is just a wrapper around the `State` effect ([defined here](https://github.com/google-research/dex-lang/blob/main/lib/prelude.dx#L535-L540)). It creates a reference a mutable cell containing the carried state. But we can only have references to things that we represent at runtime. For example, you can't have a reference to a function (e.g. see #609). Currently the compiler crashes if that constraint is violated, but we want to add a `Data` type class that lets the type checker check it. The type of `scan` would then be
`scan : [Data a]  a -> (n->a->(a&b))  -> (a & (a=>b))`.
So if you tried to run a scan where the carried state is a function, you'd see an error like "Could not synthesize `Data (Int -> Float)`" rather than a compiler crash.

But in your case, `Thing` is isomorphic to `Float`, so surely we should be able to create a `Ref h Thing` reference, right? That leads us to the second problem, which is that the current compiler doesn't know how to create references to records. That's a separate thing we need to fix. I think the main reason we haven't done it yet is that we know it'll be easier to do once we solve the first issue of making a proper class for `Data`.

So we need to do two things here:
  (1) Require a `Data a` constraint whenever you have a `Ref h a`, to rule out references to functions and other non-storable things.
  (2) Implement `Data` instances for records and variants.

**Comment by dougalm** [comment] 2021-11-22 22:46
> Also, not exactly related but writing scan_over_2 $ for i: (Fin 3=>Float). 1.0 throws

I just realized I didn't address this second question. As it turns out, they are kinda related! The problem is that `(Fin 3) => Float` isn't a valid index set. (You might have meant to write `for i:(Fin 3).   ...` instead). But the error message is bad, and it's bad for reasons similar to the other case: we have an implied type class for index sets, but the front-end type checker doesn't enforce it, so you get bad compiler crashes when it isn't satisfied. We ought to have an `Ix n` type class for index sets, just like we should have a `Data a` class for referenceable things.  #680 tracks both of these, and we should really prioritize fixing it because it's often one of the first things that users end up running into.

**Comment by sschoenholz** [comment] 2021-11-23 00:18
Thanks @dougalm! As you guessed, I came across this issue while trying to see what it would look like to bring some MD code into dex. Actually, this is a simplified repro where the actual data record is
```
data FireDescentState n:Type dim:Type = MkFireDescentState {
     R:     (n=>dim=>Float) &
     V:     (n=>dim=>Float) &
     F:     (n=>dim=>Float) &
     dt:    Float                     &
     alpha: Float                  &
     n_pos: Int
}
```
In either case, I would expect to be able to create a Ref to the state right (since arrays are just pointers to data)?

Thanks for explaining the issue so carefully. It all sounds great. No rush adding these features to dex, but let me know when they're in and I'll start using loops of records. Also, thanks for pointing out that I was defining the index set incorrectly in the for loop; my bad! 

Anyway, really liking dex so far. The notation really blurs the line between writing math and writing code in a nice way.

**Comment by dougalm** [comment] 2021-11-23 04:14
Ok, it actually turns out that record references were mostly implemented already and we were just missing a case in the type checker, which #696 adds. `scan_over [1.0, 2.0, 3.0]` should now work.

**Comment by sschoenholz** [comment] 2021-11-23 08:17
Awesome! Thanks for the quick fix. 

If you're interested, [here's](https://gist.github.com/sschoenholz/fed2f25d4a1b5b61c1a1c981cfe5f903) what I have so far. If you take a look and anything seems not canonical / bad let me know!

**Comment by apaszke** [comment] 2021-11-23 10:43
This is super cool @sschoenholz! I skimmed over the code and it all looks very idiomatic. The only thing that might be worth simplifying is the `get_position` function, which I think should be equivalent to `getAt #R` (`getAt #foo {foo=1, bar=2.0}` evaluates to `1`; you can check out `examples/isomorphisms.dx` for a longer description of how this works but it's a little involved).

**Comment by sschoenholz** [comment] 2021-11-23 15:48
Thanks @apaszke! Actually I had tried to use `getAt` and I thought maybe it only applied to dictionaries (if that's the right name in dex) rather than also to data records. When I try the following code,
```
 data Thing = T {a: Float & b:Float}
 thing = T {a=1.0, b=2.0}
 
 getAt #a thing
```
I get the error
```
> Type error:
> Expected: {a: a & ...b}
>   Actual: Thing
> (Solving for: [a:Type, b:Fields])
>
> getAt #a thing
>                ^^^^^
```
Am I using `getAt` incorrectly?

**Comment by apaszke** [comment] 2021-11-26 11:48
Ah I see now. The problem is that `getAt #a` can only project out fields of records, but when you say
```
data Thing = T {a: Float & b: Float}
```
then what you really declare is a type `Thing` that has a single constructor `T` that has a single field of type `{a: Float &  b:Float}`. Dex does not follow the Haskell convention of `data` definitions with record fields that get flattened into a single data type. So, if you wanted to use `getAt` you could do this:
```
def unThing (T x: Thing) : _ = x

thing = T {a=1.0, b=2.0}
getAt #a $ unThing thing
```
But I'm not sure how much better this is compared to what you already did 😕 We should try to come up with a better story for projections/lenses that also includes support for `data` types.

**Comment by axch** [comment] 2022-05-22 05:40
Looks like the original issue for this Issue has since been fixed, so I'm going to close this.  Is there a clear feature request for projections/lenses at the end of the discussion here?  If so, let's file it as a separate issue.

**Closed by axch** 2022-05-22 05:40 UTC
