### ISSUE TITLE
Compiler bug! Please report this

### ISSUE THREAD

**Issue by pharringtonp19** [google-research/dex-lang#962] opened 2022-06-14 20:38 UTC
I was playing around too see if I could answer my own question about [composing](https://github.com/google-research/dex-lang/discussions/936) functions and ran into this compiler bug.

Note: I don't understand how the effect system works so the code might not make much sense 

```
def (.*.) (f : Float -> Float) (g : Float -> Float) : Float -> Float =
  \x. g (f x)

def square (x: Float) : Float = 
    x * x

def (.**.)  (num_comps:Nat)  (f : Float -> Float) : Float -> Float = 
    with_state f $ \total.
        for i:(Fin num_comps).
            total := (get total) .*. f  
        (get total)
        
:t (.**.)
(Nat -> (Float32 -> Float32) -> Float32 -> Float32)

:t 2 .**. square
Compiler bug!
Please report this at github.com/google-research/dex-lang/issues

not implemented: (Float32 -> Float32)
CallStack (from HasCallStack):
  error, called at src/lib/Imp.hs:1047:8 in dex-0.1.0.0-6YSqRVo9AYNCATbpRfLD0m:Imp
```

**Comment by axch** [comment] 2022-06-16 21:06
Yes, for this particular operator you do need to be sure to add enough arguments that you're not trying to use `with_state` to construct a function.  I don't know how common of an issue this would be for other point-free snippets you might try.

**Comment by apaszke** [comment] 2022-06-20 11:19
Note that in many other functional languages, you'd be better off not defining the "compose n times" function in terms of function composition, but in terms of iterating the function once it's applied to an argument. The first one would likely result in an allocation of a big closure, while the latter could compile to a straightforward loop. Dex is definitely designed with pointful programming in mind, while providing some support for pointfree constructions. But, as @axch noted, functions are not fully first-class in Dex, because they're generally complicated to represent on systems such as GPUs. We actually eliminate all polymorphism as part of our compilation strategy, and allowing references to functions would make that impossible in certain cases. 

I'll close this for now, because it's a duplicate of #609. But thanks a lot for reporting this!

**Closed by apaszke** 2022-06-20 11:19 UTC
Labels: language / type system

**Comment by apaszke** [comment] 2022-06-22 09:05
I wouldn't say that pointfree style is necessarily discouraged. For example, you can successfully work with pointfree array combinators (without using the `.` operator in your program), because arrays are first-class throughout the compilation process. Functions, however, aren't.

To be able to compile efficiently to a variety of platforms, we often need to be able to resolve all function applications statically, which outrules things like data-dependent function construction. So, if we're talking about pointfree programming _with functions_, then the answer is that it will only work if Dex can statically derive the eventual code to be applied. So, `f3 = f ... f ... f` is ok, because Dex will clearly see that it's just `f` applied three times. But it would not be possible to do this
```
withState id \fref.
  for i:(Fin n).
    fref := get fref ... f'
```
because in that case the `n` might be a dynamic value and Dex would not be able to deduce what the final value of `fref` will be.
