### ISSUE TITLE
Parse error crashes the REPL

### ISSUE THREAD

**Issue by agrue** [google-research/dex-lang#528] opened 2021-04-19 21:25 UTC
I've found a way to crash the REPL via a very specific bad parse. I triggered this by trying to use the (nonexistent) `:help` command:

```
>=> :help
... 
... asdf
dex: This shouldn't happen:
Parse error:3:1:
  |
3 | asdf
  | ^
unexpected 'a'
expecting end of input or end of line

CallStack (from HasCallStack):
  error, called at src/lib/Parser.hs:60:13 in dex-0.1.0.0-3TQe6uju44BJFUXpaseRHY:Parser
```

To be clear, the input is `:help<Enter>`, `<Enter>` (blank line), `asdf<Enter>`. Without the blank line in the middle it doesn't crash:

```
>=> :help
... asdf
Parse error:1:6:
  |
1 | :help
  |      ^
unrecognized command: "help"

>=>
```

It looks like the `sourceBlock` parser is assumed to be infallible, but it does fail in this specific case. So the short term solution would be to find the hole and plug it. Longer term, it seems like a shame to have to rely on the parser being infallible. It would be nicer to be able to only have one error case instead of two (parse error vs. parser returns `UnParseable`). But I'm brand new to the codebase so I have no idea if this is realistic.

**Comment by axch** [comment] 2022-08-23 19:09
Looks like some time between then and now this particular crash disappeared (possibly in my recent parser reorg #1013, possibly earlier).  While the general advice not to assume infallibility is certainly good, I'm going to close this issue as resolved (#1023 adds a regression test for this example).

**Closed by axch** 2022-08-23 19:09 UTC
Labels: bug, language / parser
