### ISSUE TITLE
More build errors on Mac

### ISSUE THREAD

**Issue by duvenaud** [google-research/dex-lang#208] opened 2020-08-22 17:28 UTC
After commit 9255389b19cec10ba9d89072f3d3e5f6e8fcad53, building on my Mac fails.

The first error was 
```
clang++ -fPIC -std=c++11 -fno-exceptions -fno-rtti -c -emit-llvm src/lib/dexrt.cpp -o src/lib/dexrt.bc
src/lib/dexrt.cpp:25:42: error: use of undeclared identifier 'aligned_alloc'
  char* result = reinterpret_cast<char*>(aligned_alloc(alignment, nbytes));
```
which I found a fix for.  Apparently ```aligned_alloc``` was introduced in C++17, so I just needed to change line 35 in ```makefile``` to
```
CXXFLAGS := $(CFLAGS) -std=c++17 -fno-exceptions -fno-rtti
```

However, after that when I run ```make```, the build fails when compiling ```LLVMExec```:

```
clang++ -fPIC -std=c++17 -fno-exceptions -fno-rtti -c -emit-llvm src/lib/dexrt.cpp -o src/lib/dexrt.bc
stack build 
Building all executables for `dex' once. After a successful build of all of them, only specified executables will be rebuilt.
dex> configure (lib + exe)
Configuring dex-0.1.0.0...
dex> build (lib + exe)
Preprocessing library for dex-0.1.0.0..
Building library for dex-0.1.0.0..
[ 1 of 28] Compiling Array
[ 2 of 28] Compiling CUDA
[ 3 of 28] Compiling Cat
[ 4 of 28] Compiling Env
[ 5 of 28] Compiling PipeRPC
[ 6 of 28] Compiling Plot
[ 7 of 28] Compiling Util
[ 8 of 28] Compiling Syntax
[ 9 of 28] Compiling PPrint
[10 of 28] Compiling Type
[11 of 28] Compiling Parser
[12 of 28] Compiling Logging
[13 of 28] Compiling MDImp
[14 of 28] Compiling Flops
[15 of 28] Compiling JIT
[16 of 28] Compiling LLVMExec

--  While building package dex-0.1.0.0 using:
      /Users/bmo/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 build lib:dex exe:dex --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure (-11)
make: *** [build] Error 1
```

**Comment by apaszke** [comment] 2020-08-24 09:10
Ugh, `aligned_alloc` is in C11, but only in C++17 🤦‍♂️  I think it will be simpler for us to just switch to `posix_memalign` which should be more widely available. The second error is quite cryptic, so I'm not sure what's going on. I'll investigate today.

**Comment by apaszke** [comment] 2020-08-24 22:06
Ok, I've reproduced this. I guess the reason for the cryptic error message is that exit code `-11` implies that it was a segfault somewhere inside GHC...

**Comment by duvenaud** [comment] 2020-08-25 01:17
It's compiler bugs all the way down :)  Maybe it'd be easier for me to just change my OS.

I sometimes give a depressing speech to my grad students about how if they stay in research they'll probably spend most of their careers using bleeding-edge, barely-working tools, because once they work then we immediately pick all the new low-hanging fruit and then go back to upgrading our tools...

**Comment by apaszke** [comment] 2020-08-25 08:46
Yeah I'm pretty sure it's some GHC bug related to TemplateHaskell. Commenting out the `$(embedFile "src/lib/dexrt.bc)` template makes the code compile, but of course it won't work...

**Comment by apaszke** [comment] 2020-08-25 13:46
This should be fixed in `main`.

**Closed by apaszke** 2020-08-25 13:46 UTC

**Comment by duvenaud** [comment] 2020-08-25 17:36
Yes, it builds and tests pass now for me.  Thanks again for being so responsive!
